# Generated by Django 5.2 on 2025-05-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_sale_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='Sale_id',
        ),
    ]
