# Generated by Django 5.2 on 2025-05-02 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_trustedcustomer'),
        ('sales', '0004_remove_sale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.trustedcustomer'),
        ),
    ]
