# Generated by Django 5.2 on 2025-05-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='due_date',
            new_name='credit_due_date',
        ),
    ]
