# Generated by Django 5.2 on 2025-05-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_due_date_sale_credit_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='credit_due_date',
            new_name='due_date',
        ),
    ]
