# Generated by Django 5.2 on 2025-05-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_rename_credit_due_date_sale_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='nin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
