# Generated by Django 5.2 on 2025-05-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale_customer_name_sale_nin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='nin',
        ),
    ]
